On ignore les besoins/thématiques inexistants dans les suggestions
betagouv/dora-back pull request #129
Opened 2023-04-12 15:39 UTC by AlexandreCantin

https://trello.com/c/wmgCH12f/688-corriger-la-page-de-validation-des-contributions

2023-04-12 15:39 UTC, AlexandreCantin commented
![](https://github.trello.services/images/mini-trello-icon.png) [Corriger la page de validation des contributions](https://trello.com/c/wmgCH12f/688-corriger-la-page-de-validation-des-contributions)

2023-04-13 12:33 UTC, cedricr requested changes

2023-04-13 12:33 UTC, cedricr commented on dora/service_suggestions/models.py
> +                return [m for m in models if m]
Je pense que peux remplacer ces deux lignes par
`return Model.objects.filter(value__in=values)`

Mieux, tu peux remplacer tout le contenu de la méthode values_to_objects par cette ligne... On n'a pas besoin de limiter à ServiceSubCategory et ServiceCategory, ça peut être utile pour les autres aussi

2023-04-13 15:26 UTC, cedricr approved these changes

2023-04-13 18:25 UTC, merged