Mise à jour des services en masse depuis les modèles
betagouv/dora-back pull request #136
Opened 2023-05-17 14:41 UTC by AlexandreCantin

https://trello.com/c/kBWAkQIa/627-mise-%C3%A0-jour-en-masse-des-services-via-les-mod%C3%A8les

2023-05-23 12:55 UTC, AlexandreCantin commented
![](https://github.trello.services/images/mini-trello-icon.png) [Mise à jour en masse des services (via les modèles)](https://trello.com/c/kBWAkQIa/627-mise-%C3%A0-jour-en-masse-des-services-via-les-mod%C3%A8les)

2023-06-02 11:09 UTC, cedricr requested changes

2023-06-02 11:09 UTC, cedricr commented on dora/services/views.py
> +                        setattr(service, field, getattr(model, field))
hum, tu synchronises pas tout là; tu devrais pas passer par ta méthode `synchronize_service_from_model` plutôt?

Y a d'autres trucs qui me dérangent:
- pas d'historique de modération (log_note) ajouté
- pas d'historique de modification (ServiceModificationHistoryItem) ajouté
- et pas de vérification des droits. Ça c'est peut-être normal... on considère que quelqu'un qui a les droits d'écriture sur un modèle les a aussi forcement sur les services liés, même s'ils ne sont pas dans le même structure, etc, etc.? À revérifier...

2023-06-08 08:54 UTC, cedricr requested changes

2023-06-08 08:54 UTC, cedricr commented on dora/services/views.py
> +                service = Service.objects.get(slug=service_slug)
il faut gérer le cas où les slugs ne sont pas trouvés

2023-06-08 08:54 UTC, cedricr commented on dora/services/views.py
> +                    service.model = model
hum, non il n'y a aucune raison de changer le modèle ici il me semble?

2023-06-08 08:54 UTC, cedricr commented on dora/services/views.py
> +        sync_checksum = update_sync_checksum(model)
je vois pas l'intérêt de cette modification?

2023-06-08 08:54 UTC, cedricr commented on dora/services/views.py
> +                    service.log_note(self.request.user, "Service modifiée")
```suggestion
                    service.log_note(self.request.user, f"Service modifié automatiquement suite à la mise à jour de son modèle ({' / '.join(changed_fields)})")
```

2023-06-08 08:54 UTC, cedricr commented on dora/services/views.py
> +                        setattr(service, field, getattr(model, field))
> dans la mesure où on avait changed_fields, je ne voyais pas l'intérêt de passer par synchronize_service_from_model

Ça n'aurait pas géré les champs M2M correctement.

2023-06-08 09:05 UTC, AlexandreCantin commented on dora/services/views.py
> +        sync_checksum = update_sync_checksum(model)
Ça sent le remplacement un peu trop brutal… 😓

2023-06-08 09:16 UTC, cedricr commented on dora/services/views.py
> +        sync_checksum = update_sync_checksum(model)
oui oui, mais tu aurais pu faire service.last_sync_checksum = model.sync_checksum; c'est du détail, mais on introduit en général une variable intermédiaire pour clarifier une intention ou pour éviter un recalcul, ici ça ne fait ni l'un ni l'autre. (et 'sync_checksum' l. 507 est moins compréhensible que 'model.sync_checksum')

2023-06-09 16:00 UTC, cedricr requested changes

2023-06-12 07:31 UTC, AlexandreCantin commented on dora/services/views.py
> +        sync_checksum = update_sync_checksum(model)
Ok je comprends mieux la remarque 🙂

2023-06-12 15:26 UTC, cedricr approved these changes

2023-06-13 07:13 UTC, merged