feat: ajout d'un script d'import garages mes aides
betagouv/dora-back pull request #14
Opened 2022-03-14 22:40 UTC by vmttn

2022-03-15 12:58 UTC, cedricr requested changes

2022-03-15 12:58 UTC, cedricr commented on dora/structures/management/commands/import_mes_aides.py
> +            structure_source, _ = StructureSource.objects.update_or_create(
C'est pas idéal je trouve; 

- pourquoi par get_or_create plutôt?
- dans les deux cas, si qq a édité le label, ça va tenter d'en recréer un.
Donc peut-être plutot StructureSource.objects.get_or_create(value="MESAIDES",defaults={"label": "API Mes Aides"})

Par ailleurs, pour les ids, je pense plutot me diriger vers qq chose qui ressemble à des slugs, plus lisibles. Donc 'api-mes-aides' peut-être?

2022-03-15 12:58 UTC, cedricr commented on dora/structures/management/commands/import_mes_aides.py
> +                structure, created = Structure.objects.get_or_create(
Eventuellement, au lieu de faire ça:
- juste un get pour voir si ça existe
- si ça n'existe pas, Structure.objects.create_from_establishment(establishment)
L'avantage, c'est que ça préremplira les champs à partir de la base SIRENE s'ils sont vides dans l'import.

2022-03-15 12:58 UTC, cedricr commented on dora/structures/management/commands/import_mes_aides.py
> +                structure.department = garage_data["zipcode"][
non, il vaut mieux partir du code insee de l'establishment. Tu ne peux pas déterminer un département à partir d'un code postal
`from dora.core.utils import code_insee_to_code_dept`

2022-03-15 12:58 UTC, cedricr commented on dora/structures/management/commands/import_mes_aides.py
> +                structure.typology = StructureTypology.objects.get(
Il vaut mieux laisser vide (à moins qu'Agathe te dise qu'on sait que les garages solidaires sont tous des XXX), mais je ne pense pas que c'est le cas.
Other => aucune de nos catégories
Vide => pas (encore) renseigné

2022-03-15 12:58 UTC, cedricr commented on dora/structures/management/commands/import_mes_aides.py
> +                structure.name = garage_data["name"]
éventuellement 
```suggestion
                structure.name = garage_data["name"][:255]
```
et même chose pour la suite

2022-03-15 12:58 UTC, cedricr commented on dora/structures/management/commands/import_mes_aides.py
> +                # garaga_data sometimes contains 2 concatenated phone numbers
commentaires en français ;-)

2022-03-15 12:58 UTC, cedricr commented on dora/structures/management/commands/import_mes_aides.py
> +                structure.phone = "".join(
pas sûr de comprendre ce que tu veux faire ici; mets un commentaire plus complet peut-etre?

2022-03-15 12:58 UTC, cedricr commented on dora/structures/management/commands/import_mes_aides.py
> +                if created:
Tout la question est: qu'est-ce qu'on fait si la structure est déjà créée? On ne veut sans doute pas écraser les données déjà rentrées dans Dora, **surtout** si c'est des données remplies par un utilisateur.
Est-ce qu'on ne rempli que les champs vides dans ce cas? Aucun?
A discuter avec le metier.

2022-03-15 12:58 UTC, cedricr commented on dora/structures/management/commands/import_mes_aides.py
> +                structure.address1 = establishment.address1
assez d'accord pour utiliser les données SIRENE plutot que les données de l'import… mais ça peut se discuter.

2022-03-15 12:58 UTC, cedricr commented on dora/structures/management/commands/import_mes_aides.py
> +                service = Service.objects.create(
On peut faire mieux (lieux de déroulement, etc). A voir avec le métier, est-ce qu'on créé effectivement un service dans ce cas, ou juste la structure?

2022-03-16 09:47 UTC, vmttn commented on dora/structures/management/commands/import_mes_aides.py
> +            structure_source, _ = StructureSource.objects.update_or_create(
Done.
Pour les ids, je pense que c'est suffisamment lisible pour ne pas faire de changements mais c'est comme tu préfères. Je laisse tel quel pour l'instant

2022-03-16 10:16 UTC, vmttn commented on dora/structures/management/commands/import_mes_aides.py
> +                structure.department = garage_data["zipcode"][
TIL
https://fr.wikipedia.org/wiki/Liste_des_communes_de_France_dont_le_code_postal_ne_correspond_pas_au_d%C3%A9partement et la Corse, c'est bien ça ?

2022-03-16 10:28 UTC, vmttn commented on dora/structures/management/commands/import_mes_aides.py
> +                structure.phone = "".join(
J'ajoute : "On garde le premier numéro."
Sur l'implémentation, je match les 5 premieres paires de chiffres et je les concatène.

2022-03-16 11:38 UTC, vmttn commented on dora/structures/management/commands/import_mes_aides.py
> +                if created:
ok en attendant d'y voir plus clair coté métier je ne laisse que le cas dune création
a terme on pourrait prendre en compte la source, le dernier editeur et comparer si possible les dates de modifs (pas dans les données mes aides actuellement)

2022-03-16 11:46 UTC, cedricr commented on dora/structures/management/commands/import_mes_aides.py
> +                structure.department = garage_data["zipcode"][
exactement. Ça reste mineur, mais quand on a l'info correcte…

2022-03-16 11:55 UTC, cedricr commented on dora/structures/management/commands/import_mes_aides.py
> +                structure.phone = "".join(
ok, ça ne va pas marcher si tu as deux numéros courts (3625, 3728); mais c'est un detail. C'est pas toujours le même séparateur? Auquel cas garder le 1 elt du split sur le séparateur me semblerait plus lisible.

2022-05-05 13:10 UTC, cedricr commented
@vmttn même chose, à migrer dans D.I. ?

2022-05-25 14:11 UTC, closed without merging