Possibilité de préciser son activité sur Dora
betagouv/dora-back pull request #146
Opened 2023-06-26 13:06 UTC by AlexandreCantin

https://trello.com/c/p7wafxWP/766-qualifier-le-profil-des-utilisateurs-inscrits

2023-06-26 13:23 UTC, AlexandreCantin commented
![](https://github.trello.services/images/mini-trello-icon.png) [Qualifier le profil des utilisateurs inscrits](https://trello.com/c/p7wafxWP/766-qualifier-le-profil-des-utilisateurs-inscrits)

2023-06-27 09:31 UTC, cedricr requested changes

2023-06-27 09:31 UTC, cedricr commented on dora/users/views.py
> +    setattr(request.user, "main_activity", request.data.get("main_activity"))
idéalement, tu passerais par un serializer pour valider la valeur entrante de request.data.get("main_activity"), et tu rajouterais des tests...

2023-06-27 09:31 UTC, cedricr commented on dora/users/views.py
> +    return Response("ok", status=200)
```suggestion
    return Response(status=204)
```
Non ça ne rime à rien de renvoyer "ok". Soit tu renvoies l'objet modifié, avec un code 200, soit tu ne renvoies rien, avec un code 204

2023-06-27 09:31 UTC, cedricr commented on config/urls.py
> +    path("profile/update-main-activity/", dora.users.views.update_main_activity),
```suggestion
    path("profile/main-activity/", dora.users.views.update_main_activity),
```

2023-06-27 09:31 UTC, cedricr commented on dora/users/views.py
> +@api_view(["PATCH"])
```suggestion
@api_view(["PUT", "PATCH"])
```

2023-06-27 09:39 UTC, cedricr commented on dora/users/views.py
> +    setattr(request.user, "main_activity", request.data.get("main_activity"))
le mieux à mon avis c'est que tu repartes de ce qui existait avant ici: https://github.com/betagouv/dora-back/commit/d3934eeea4f0e7fb5a1f07166105418367745ad1

2023-06-27 14:23 UTC, cedricr requested changes

2023-06-27 14:23 UTC, cedricr commented on dora/users/views.py
> +@api_view(["PATCH"])
Tout à fait quand tu fais des opérations REST sur une ressource, tu vas en général faire un POST pour une nouvelle ressource, un PUT pour modifier une ressource, et un DELETE pour la supprimer.
Ça me parait bizarre d'avoir une API te permettant de faire un PATCH qui ne te permet pas aussi de faire un PUT, c'est le client qui choisit s'il change tout ou juste un élément.

Par contre ici, on n'est pas sur une opération REST classique (sinon ton url serait plutot /user/<userid>) ou équivalent; c'est une action; et le POST est plus approprié dans ce cas. Qu'est-ce que ça veut dire de faire un PATCH sur une ressource qui en soi n'existe pas (tu ne peux pas faire de GET sur cette URL...)

2023-06-27 14:23 UTC, cedricr commented on dora/users/views.py
> +    request.user.main_activity = request.data.get("main_activity")
```suggestion
    request.user.main_activity = serializer.validated_data["main_activity"]
```

2023-06-27 14:23 UTC, cedricr commented on dora/users/views.py
> +            "main_activity",
Ouais mais non... Tu veux un serializer juste pour main_activity, plus pour les autres champs...
Ce UserProfileSerializer n'était plus utilisé a priori, il avait juste été oublié quand on avait abandonné les mises à jour de profile. Je voulais juste te dire de t'inspirer du code de l'époque.

2023-06-27 15:44 UTC, AlexandreCantin commented on dora/users/views.py
> +            "main_activity",
Du coup, je suis parti sur 

```
class UserMainActivitySerializer(serializers.ModelSerializer):
    class Meta:
        model = User
        fields = ["main_activity"]
```

2023-06-28 08:29 UTC, cedricr requested changes

2023-06-28 08:29 UTC, cedricr commented on dora/users/views.py
> +@sensitive_post_parameters(["main_activity"])
c'est pas un parametre sensible... tu peux virer cette ligne

2023-06-28 08:29 UTC, cedricr commented on dora/users/tests.py
> +    def test_main_activity_is_correctly_updated_but_not_the_first_name(self):
du coup ce test n'a plus vraiment de sens

2023-06-28 09:06 UTC, cedricr approved these changes

2023-06-28 09:58 UTC, merged