Gestion et validation des CGU
betagouv/dora-back pull request #154
Opened 2023-07-25 09:16 UTC by AlexandreCantin

https://trello.com/c/3qZTwWcb/781-validation-des-nouvelles-cgu-pour-les-anciens-inscrits

2023-07-25 09:18 UTC, AlexandreCantin commented
![](https://github.trello.services/images/mini-trello-icon.png) [Validation des nouvelles CGU pour les anciens inscrits](https://trello.com/c/3qZTwWcb/781-validation-des-nouvelles-cgu-pour-les-anciens-inscrits)

2023-07-25 16:48 UTC, cedricr commented
> La question se pose concernant ceux qui auraient accepté les CGU après ce ticket ([betagouv/dora-front@4502b92](https://github.com/betagouv/dora-front/commit/4502b92c16088e4e5c3c57dcb2143f5ad351b4b2)) => on met une valeur par défaut ou non ? thinking

Dans le doute on leur demande de revalider; donc à mon avis on demande a tout le monde de revalider pour l'instant

2023-07-25 17:07 UTC, cedricr requested changes
Le numéro de version doit venir du front

2023-07-25 17:07 UTC, cedricr commented on config/settings.py
> +CURRENT_CGU_VERSION = os.environ["CURRENT_CGU_VERSION"]
En fait je pense que je préfèrerais que la version vienne du front; le front connait sa version courante des CGUs (pour l'instant elle est hardcodée dans le content.md, mais on peut le gérer comme il faut), et il veut savoir si l'utilisateur a validé cette version là.
Si on met ça dans une variable d'environnement, et en back en plus, on peut tout à fait enregistrer le fait qu'il a validé une version qui **n'est pas celle que le front lui a montrée**

2023-07-25 17:07 UTC, cedricr commented on dora/rest_auth/views.py
> +        user.cgu.update({settings.CURRENT_CGU_VERSION: str(timezone.now())})
peut-être stocker une version de date plus "normée", .isoformat() par exemple

2023-07-29 17:24 UTC, cedricr requested changes

2023-07-29 17:24 UTC, cedricr commented on dora/users/models.py
> +    cgu = models.JSONField(default=dict)
cgu_versions_accepted?

2023-07-29 17:24 UTC, cedricr commented on dora/rest_auth/views.py
> +    user.cgu.update({cgu_version: timezone.now().isoformat()})
il faut faire gaffe de ne pas écraser une acceptation existante. Ex: j'accepte la v3 le 1er janvier.  Je la reaccepte le 10 janvier. On ne saura plus qu'entre le 1er et le 10 tu l'avais déjà acceptée.

2023-07-29 17:24 UTC, cedricr commented on dora/rest_auth/serializers.py
> +    cgu_version = serializers.CharField(required=False)
Pourquoi ce n'est pas requis?

2023-08-07 10:13 UTC, AlexandreCantin commented on dora/rest_auth/serializers.py
> +    cgu_version = serializers.CharField(required=False)
Alors il y a deux pages dans le front qui appelle `api...auth/join-structure` =>
- `auth/invitation` => avec `structureSlug` comme paramètre
- `auth/rattachment` => avec `siret` et `cguVersion` avec comme paramètres

Du coup, `cguVersion` est nécessaire dans `auth/rattachment` mais pas dans `auth/invitation`

J'ai rendu `cguVersion` obligatoire en présence du `siret`.
Après, on peut diviser cette route en deux et modifier le front en conséquence 🤔

2023-08-07 12:23 UTC, cedricr commented on dora/rest_auth/serializers.py
> +    cgu_version = serializers.CharField(required=False)
Hum, mais la question alors c'est plutot pourquoi /auth/invitation ne passe pas cguVersion ? (je ne dis pas qu'il n'y a pas une bonne raison, juste qu'a priori je ne la vois pas !)

2023-08-07 12:29 UTC, cedricr requested changes

2023-08-07 12:29 UTC, cedricr commented on dora/rest_auth/serializers.py
> +            cgu_version = data.get("cgu_version")
ça rejoins l'autre commentaire que j'ai mis, mais pas sûr de voir pourquoi le fait de passer un numéro de version depend du fait qu'on passe un siret ou un slug à cette route.

2023-08-07 12:29 UTC, cedricr commented on dora/rest_auth/serializers.py
> +                raise serializers.ValidationError("Expecting `cgu_version`")
Message en français (c'est sans doute pas toujours  le cas dans le code, mais on tend plutot vers ça maintenant)

2023-08-07 12:29 UTC, cedricr commented on dora/users/migrations/0023_rename_cgu_user_cgu_versions_accepted.py
> +from django.db import migrations
autant faire une seule migration par PR dans la mesure du possible.

2023-08-08 07:58 UTC, AlexandreCantin commented on dora/rest_auth/serializers.py
> +            cgu_version = data.get("cgu_version")
![rattachment-1](https://github.com/betagouv/dora-back/assets/1846641/40026733-2781-4847-a9fd-fd22c74d5497)

![invitation-1](https://github.com/betagouv/dora-back/assets/1846641/4e49376a-c869-4f4b-8086-06890b9a281d)

En fait, dans les deux pages, c'est la route `api...auth/join-structure` qui est appelé et dans le deuxième cas, la validation des CGU ne me semble pas nécessaire car le membre est déjà présent sur Dora…

2023-08-08 09:32 UTC, AlexandreCantin commented on dora/rest_auth/serializers.py
> +    cgu_version = serializers.CharField(required=False)
J'ai vu avec Andrei et `/auth/invitation` doit aussi valider les CGU - le paramètre va devenir obligatoire :)

2023-08-08 12:13 UTC, cedricr approved these changes

2023-08-08 13:58 UTC, merged