feat: ajout de commandes d'import itou
betagouv/dora-back pull request #17
Opened 2022-03-16 17:24 UTC by vmttn

2022-03-17 18:04 UTC, cedricr commented
Pas encore regardé, mais les antennes sont maintenant mergées sur main, tu peux avancer si tu veux

2022-03-23 12:01 UTC, cedricr requested changes
Une première partie de review — je n'ai pas encore regardé les SIAE. Quelques commentaires mais c'est top pour l'instant.

2022-03-23 13:46 UTC, cedricr requested changes

2022-03-23 13:46 UTC, cedricr commented on dora/structures/management/commands/import_itou_siae.py
> +                    logger.debug(f"{siret} probablement fermé. Ignoré")
le debug n'est pas forcement suffisant ici; ça serait pas mal d'afficher l'url https://annuaire-entreprises.data.gouv.fr/entreprise/<siret> pour pouvoir vérifier d'un clic si c'est un établissement fermé, si c'est trop récent et que notre base sirene n'est pas à jour, ou si c'est une erreur de sirene.
Ou alors, on pourrait aussi faire une requete d'API 
https://entreprise.data.gouv.fr/api/sirene/v3/etablissements/<siret>
doc: https://entreprise.data.gouv.fr/api_doc/sirene

2022-03-23 13:46 UTC, cedricr commented on dora/structures/management/commands/import_itou_siae.py
> +                        if antenne_datum["description"] != "":
utils.normalize_description va déjà marcher avec une chaine vide non? on peut donc enlever le test, ça sera plus lisible.

2022-03-23 13:46 UTC, cedricr commented on dora/structures/models.py
> +            siret=None,
pas sûr de ce siret=None
Dans le cas d'itou, oui les antennes ont un siret invalide *sauf* si on considère une structure avec typologie differente comme une antenne.
Dans le cas général, nos antennes peuvent parfaitement avoir un siret.

2022-03-23 13:46 UTC, cedricr commented on dora/structures/models.py
> +        # TODO(vmttn): dans le cas où les infos (e.g. contact) seraient
Oui tant qu'on ne sait pas ça, je ne suis pas super à l'aise avec cette methode. A mon avis c'est non.

2022-03-23 15:08 UTC, vmttn commented on dora/structures/utils.py
> +    ret = phone.replace(" ", "").replace("-", "").replace(".", "")
J'aime bien ta version ;)

Le package [phonenumbers](https://github.com/daviddrysdale/python-phonenumbers) pourrait être utile. Il sert d'implém à https://github.com/stefanfoulis/django-phonenumber-field

Ok pour `core.utils`

2022-03-23 15:47 UTC, vmttn commented on dora/structures/test_utils.py
> +import unittest
mais on aura un beau message d'erreur pour nous aider à nous en souvenir :sweat_smile:
de manière générale, je préfère ne pas faire si ça n'est pas nécessaire. Dans le cas où on aurait besoin de rajouter un test qui touche à la db, je crois que je challengerais d'abord le fait de mettre une fonction qui touche à la db dans un fichier qui contient des pure fonctions de normalisation (même si le nom n'est pas explicite pour l'instant). Peut-être renommer le module `utils` -> `utils.normalizing`

2022-03-23 16:01 UTC, vmttn commented on dora/structures/management/commands/import_itou_org.py
> +                structure.typology = StructureTypology.objects.get(value=datum["kind"])
on devra certainement réfléchir à la gestion des erreurs.
là actuellement, pour une erreur pareille, l'exception remonte et la transaction rollback.

2022-03-24 11:47 UTC, vmttn commented on dora/structures/management/commands/import_itou_org.py
> +                    structure.longitude, structure.latitude = utils.normalize_coords(
done

2022-03-24 11:49 UTC, vmttn commented on dora/structures/models.py
> +        # TODO(vmttn): dans le cas où les infos (e.g. contact) seraient
ok avec toi

2022-03-28 12:05 UTC, vmttn commented on dora/structures/management/commands/import_itou_org.py
> +                            distance=RawSQL(
cf issue en dette technique dans le backlog

2022-03-28 12:08 UTC, vmttn commented on dora/structures/models.py
> +            siret=None,
ok je laisse la possiblité de passer le siret en kwarg

2022-03-28 12:56 UTC, vmttn commented on dora/structures/management/commands/import_itou_siae.py
> +                    logger.debug(f"{siret} probablement fermé. Ignoré")
Je pense qu'on anticipe un peu là, mais c'est ajouté ;)

2022-03-30 09:09 UTC, vmttn commented on dora/structures/models.py
> +    geocoding_score = models.FloatField(blank=True, null=True)
oui :) j'attendais avant le dernier moment en anticipant les conflits avec de nouvelles migrations sur main

2022-03-31 18:14 UTC, merged