Recherche multi-catégories et sous-catégories
betagouv/dora-back pull request #92
Opened 2022-10-26 15:05 UTC by AlexandreCantin

https://trello.com/c/uUoPoccm

2022-10-28 14:57 UTC, cedricr approved these changes

2022-10-28 14:59 UTC, cedricr commented
> Question pour @cedricr : est-ce que je casse une API avec ce changement ? thinking

Ça m'a l'air compatible avec l'existant, et c'est une API privée... donc go ;-)

2022-10-28 15:50 UTC, cedricr requested changes

2022-10-28 15:50 UTC, cedricr commented on dora/services/views.py
> +        subcategories = categories.split(",")
```suggestion
        subcategories = subcategories.split(",")
```

2022-10-28 15:50 UTC, cedricr commented on dora/services/views.py
> +        services = services.filter(kinds__value__in=kinds)
Je ne vois pas trop l'interet de rajouter cette variable intermédiaire?

2022-11-02 08:58 UTC, AlexandreCantin commented on dora/services/views.py
> +        subcategories = categories.split(",")
Ouch... 😞

2022-11-02 09:04 UTC, AlexandreCantin commented on dora/services/views.py
> +        services = services.filter(kinds__value__in=kinds)
L'idée c'était de maintenir une cohérence stylistique avec les autres paramètres...
Mais oui, pas un grand intérêt 🤷‍♂️

2022-11-02 16:54 UTC, AlexandreCantin commented on dora/services/views.py
> +        services = services.filter(kinds__value__in=kinds)
Du coup, j'ai modifié pour revenir à `services = services.filter(kinds__value__in=kinds.split(","))` et j'ai reporté cette logique aux autres paramètres 🙂

2022-11-07 11:17 UTC, AlexandreCantin commented on dora/services/views.py
> +            for s in DeploymentState.objects.filter(
Du coup, c'est validé :)

2022-11-07 16:57 UTC, cedricr requested changes

2022-11-07 16:57 UTC, cedricr commented on dora/services/views.py
> +        for subcategory in subcategories.split(","):
Je pense que ça ne va pas marcher: tu restreins le filtre à chaque nouvelle sous-catégorie, au lieu de renvoyer les resultats de chaque sous-catégorie, un ET au lieu d'un OU quoi...
Et si ce n'est pas le cas, je veux bien un test à coté de https://github.com/betagouv/dora-back/blob/921c16c1c195eb1971cad77b578afcfce64c221b/dora/services/tests.py#L1233 pour me prouver le contraire ;-)

2022-11-08 11:06 UTC, cedricr commented on dora/services/views.py
> +                    Q.OR,
je suis pas familier avec Q.OR, et je ne trouve pas la documentation. Est-ce ce que tu veux faire ce n'est pas 
subcategories_filter |= (Q(subcategories__value=subcategory)
                    | (
                        Q(categories__value=cat)
                        & ~Q(subcategories__in=all_sister_subcats)
                    ))

?

2022-11-08 11:09 UTC, cedricr commented on dora/services/tests.py
> +    def test_find_service_with_requested_cats(self):
Cool, merci! J'ai rajouté un test ici si ça te va:
https://github.com/betagouv/dora-back/pull/96

2022-11-08 15:30 UTC, cedricr approved these changes

2022-11-09 11:14 UTC, cedricr requested changes

2022-11-09 11:14 UTC, cedricr commented on dora/services/views.py
> +            if subcat == "other":
attention: reprendre la correction sur main: 
```suggestion
            if subcat == "autre":
```

2022-11-09 16:41 UTC, cedricr approved these changes

2022-11-09 16:58 UTC, merged